### ISSUE TITLE
xor filters

### ISSUE THREAD

**Issue by est31** [mozmark/rust-cascade#18]
It would be interesting to investigate usage of xor filters for crlite: https://lemire.me/blog/2019/12/19/xor-filters-faster-and-smaller-than-bloom-filters/

The authors claim they are both faster and create smaller filters than bloom filters. Probably this is true for crlite's use case as well?

**Comment by jcjones** [comment]
It probably is, indeed. The immutability of xor filters isn't an issue, so seems a prime candidate for an update and further analysis.

**Comment by est31** [comment]
Closing in favour of https://github.com/mozilla/crlite/issues/44
